name: build extension web

on:
  push:
    branches:
      - main
      - dev
#      - 'feat*'
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'


      - name: dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache
            ~/node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-dependencies-

      - name: Yarn install
        run: yarn install


      - name: build ext-web
        run: |
          yarn run build:ext-web

      - name: Upload build web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ext-web
          path: apps/web/out
          retention-days: 5


