name: CI/CD

on:
  push:
    branches:
      - main
      - feat_sync

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          yarn install

      - name: Run Tests
        run: |
          yarn run test

      - name: Build
        run: |
          yarn run build

